name = 'Basic'
license = 'MIT'
licenselink = 'https://github.com/free-explorers/free-explorers.com/blob/main/LICENSE'
description = 'A simple theme for a simple site'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/free-explorers/free-explorers.com'

# If you have a running demo of the theme
demosite = 'free-explorers.com'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'PapyElGrinco', homepage = 'https://github.com/PapyElGringo'},
  {name = 'coffandro', homepage = 'https://coffandro.github.io'}
]
