baseURL = 'https://free-explorers.com/'
languageCode = 'en-us'
title = 'Free Explorers'
theme = 'basic'

[[menus.main]]
name = 'Free Explorers'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Architects'
pageRef = '/architects'
weight = 30